name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo test default
        run: cargo test --all-targets
      - name: cargo test locking-rt
        run: cargo test --no-default-features --all-targets -F locking-rt
      - name: cargo test locking-rt-safe
        run: cargo test --no-default-features --all-targets -F locking-rt-safe
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo fmt
        run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo clippy
        run: |
          cargo clippy -F async --all-targets -- -W clippy::all -W clippy::pedantic \
          -A clippy::used-underscore-binding \
          -A clippy::doc_markdown \
          -A clippy::needless_pass_by_value \
          -A clippy::must_use_candidate \
          -A clippy::return_self_not_must_use \
          -A clippy::missing_errors_doc \
          -A clippy::single_match \
          -A clippy::uninlined_format_args \
          -A clippy::no_effect_underscore_binding
  view-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo test
        run: cd rvideo-view && sudo apt-get -y install nasm && cargo test --verbose --all-features --all-targets
  view-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo fmt
        run: cd rvideo-view && cargo fmt --check
  view-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo clippy
        run: |
          cd rvideo-view && cargo clippy --all-targets -- -W clippy::all -W clippy::pedantic \
          -A clippy::used-underscore-binding \
          -A clippy::doc_markdown \
          -A clippy::needless_pass_by_value \
          -A clippy::must_use_candidate \
          -A clippy::return_self_not_must_use \
          -A clippy::missing_errors_doc \
          -A clippy::single_match \
          -A clippy::uninlined_format_args \
          -A clippy::no_effect_underscore_binding
